# This file created by conda-build 3.12.1
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/git-2.18.0-on-linux_64, last modified Tue Aug  7 20:53:47 2018
# ------------------------------------------------

package:
    name: git
    version: 2.18.0
source:
    -   patches:
            - 0001-macOS-Do-not-use-the-system-Wish-urgh.patch
        sha256: 8b40be383a603147ae29337136c00d1c634bdfdc169a30924a024596a7e30e92
        url: https://www.kernel.org/pub/software/scm/git/git-2.18.0.tar.xz
build:
    detect_binary_files_with_prefix: true
    number: '0'
    string: pl526hb37396a_0
requirements:
    build:
        - autoconf 2.69 pl526hebd4dad_5
        - binutils_impl_linux-64 2.28.1 had2808c_3
        - binutils_linux-64 7.2.0 had2808c_27
        - gcc_impl_linux-64 7.2.0 habb00fd_3
        - gcc_linux-64 7.2.0 h550dcbe_27
        - libgcc-ng 7.2.0 hdf63c60_3
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - m4 1.4.18 h4e445db_0
        - make 4.2.1 h1bed415_1
        - perl 5.26.2 h14c3975_0
    host:
        - ca-certificates 2018.03.07 0
        - expat 2.2.5 he0dffb1_0
        - libcurl 7.61.0 h1ad7b7a_0
        - libgcc-ng 7.2.0 hdf63c60_3
        - libssh2 1.8.0 h9cfc8f7_4
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - openssl 1.0.2o h14c3975_1
        - perl 5.26.2 h14c3975_0
        - tk 8.6.7 hc745277_3
        - zlib 1.2.11 ha838bed_2
    run:
        - expat >=2.2.5,<3.0a0
        - libcurl >=7.61.0,<8.0a0
        - libgcc-ng >=7.2.0
        - openssl >=1.0.2o,<1.0.3a
        - perl 5.*
        - tk >=8.6.7,<8.7.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - test -f $PREFIX/bin/git
        - git --version
        - git clone https://github.com/conda-forge/git-feedstock
        - pushd git-feedstock
        - git submodule update --init
        - popd
        - pushd $(mktemp -d 2>/dev/null || mktemp -d -t 'tmp')
        - git init .
        - echo hello > world
        - git add world
        - echo goodbye >> world
        - echo y | git add -p world
        - popd
        - bash $PREFIX/share/bash-completion/completions/git
about:
    description: 'Git is a free and open source distributed version control system
        designed

        to handle everything from small to very large projects with speed and

        efficiency.

        '
    dev_url: https://github.com/git/git
    doc_url: https://git-scm.com/doc
    home: https://git-scm.com/
    license: GPL v2 and LGPL 2.1
    summary: distributed version control system
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - mingwandroid
        - msarahan
        - pelson
        - scopatz
