# This file created by conda-build 3.11.0
# ------------------------------------------------

package:
    name: libcurl
    version: 7.61.0
source:
    fn: curl-7.61.0.tar.bz2
    sha256: 5f6f336921cf5b84de56afbd08dfb70adeef2303751ffb3e570c936c6d656c9c
    url: http://curl.haxx.se/download/curl-7.61.0.tar.bz2
build:
    number: 0
    run_exports:
        - libcurl >=7.61.0,<8.0a0
    string: h1ad7b7a_0
requirements:
    build:
        - binutils_impl_linux-64 2.28.1 had2808c_3
        - binutils_linux-64 7.2.0 had2808c_27
        - gcc_impl_linux-64 7.2.0 habb00fd_3
        - gcc_linux-64 7.2.0 h550dcbe_27
        - libstdcxx-ng 7.2.0 hdf63c60_3
    host:
        - ca-certificates 2018.03.07 0
        - libgcc-ng 7.2.0 hdf63c60_3
        - libssh2 1.8.0 h9cfc8f7_4
        - openssl 1.0.2o h20670df_0
        - zlib 1.2.11 ha838bed_2
    run:
        - libgcc-ng >=7.2.0
        - libssh2 >=1.8.0,<2.0a0
        - openssl >=1.0.2o,<1.0.3a
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - curl-config --features
        - curl-config --protocols
about:
    description: 'Curl is an open source command line tool and library for transferring
        data

        with URL syntax. It is used in command lines or scripts to transfer data.

        '
    dev_url: https://github.com/curl/curl
    doc_source_url: https://github.com/curl/curl/tree/master/docs
    doc_url: https://curl.haxx.se/docs/
    home: http://curl.haxx.se/
    license: MIT/X derivate (http://curl.haxx.se/docs/copyright.html)
    license_family: MIT
    license_file: COPYING
    summary: tool and library for transferring data with URL syntax
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - mingwandroid
        - msarahan
        - ocefpaf
