# This file created by conda-build 3.14.4
# meta.yaml template originally from:
# /root/recipe, last modified Sat Sep 15 20:36:24 2018
# ------------------------------------------------

package:
    name: vim
    version: 8.1.0390
source:
    url: https://github.com/vim/vim/archive/v8.1.0390.tar.gz
build:
    binary_has_prefix_files:
        - bin/vim
    number: '8'
    string: py37_8
requirements:
    build:
        - ca-certificates 2018.03.07 0
        - certifi 2018.8.24 py37_1
        - libedit 3.1.20170329 h6b74fdf_2
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 8.2.0 hdf63c60_1
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - ncurses 6.1 hf484d3e_0
        - openssl 1.0.2p h14c3975_0
        - pip 10.0.1 py37_0
        - python 3.7.0 hc3d631a_0
        - readline 7.0 h7b6447c_5
        - setuptools 40.2.0 py37_0
        - sqlite 3.24.0 h84994c4_0
        - tk 8.6.8 hbc83047_0
        - wheel 0.31.1 py37_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 ha838bed_2
    run:
        - python >=3.6
test:
    commands:
        - vim --version
extra:
    final: true
